### ISSUE TITLE
Node app_name@10.56.22.85 is not running!

### ISSUE THREAD

**Issue by matiasgagliano** [gigalixir/gigalixir-run#2]
I'm trying to run Gigalixir's remote console but I always get the same error and I can't find enough information to why. I'm not sure if there's a bug, some error in my app's configuration or just poor information.

The app is running with no issues and `gigalixir ps` says `"status": "Healthy"`, so I assume the app is OK. But when running `gigalixir ps:remote_console` or `gigalixir ps:distillery remote_console` I get "Node app_name@10.56.22.85 is not running!".

I can SSH just fine into the container with `gigalixir ps:ssh`, so I tried the following in an attempt to identify or narrow the source of the issue, but still not getting much information:
-  `gigalixir_run remote_console` -> "Node app_name@10.56.22.85 is not running!"
- `/app/bin/{app_name}_rc_exec.sh remote_console` -> "Node app_name@127.0.0.1 is not running!"
- `./releases/0.1.0/{app_name}.sh remote_console` -> "Unable to configure release!"

Let me know if I should report this somewhere else of if there's something else I can do with `gigalixir_run` to try to identify the issue.

Thanks.

**Comment by jesseshieh** [comment]
@matiasgagliano do you mind if I take a look at your logs, container, and source code? If so, what's your app name? You can also send it to help@gigalixir.com

Are you using a custom vm.args file by chance? One thing you can check is 
`gigalixir ps:run -a bar bin/app_name describe` to see what name and ip the node is running as.

**Comment by matiasgagliano** [comment]
Thanks for the quick reply.

Even though the app is healthy and running I get:

```
# gigalixir ps:run -a bar bin/app_name describe 
                                                                                                  
{"errors":{"ssh":[" Sorry, it looks like no replicas are running at the moment. If your app is deployed, but unhealthy, we automatically restart it until it is healthy. If it's restarting constantly, then you probably can't SSH in. Try checking `gigalixir logs` or `gigalixir ps` to see why the app is not running. If you're trying to run migrations, try `gigalixir run mix ecto.migrate` to run it as a job."]}}
```

But, from inside the container (SSH) `/app/bin/webhub  describe` shows:

```
{app_name}-0.1.0                                              
System Info ===========================                                      
...                                                                                                                                                                                                                             
Status: stopped
                                                                                                                                                                                                                         
Release Info ==========================
Name: {app_name}_maint_@127.0.0.1
...
```

So, even though it's healthy and working it says `stopped` and _Name_ is not just the app's name, it adds `_maint_` at the end.

I have the default `vm.args` file built by Distillery, which at `/app/releases/0.1.0/vm.args` says:

```
## Name of the node
-name {app_name}@127.0.0.1
```

Let me know if this makes sense or has a clear fix, if not I can contact you with the app's information at help@gigalixir.com.

**Comment by jesseshieh** [comment]
Hm, very strange. I haven't seen this before, but I'm sure we can figure it out. I think I need your app info to debug further. Oh also, I realized I accidentally sent you a command with `-a bar` in it. You'll want to replace that with your own app name.

**Comment by matiasgagliano** [comment]
> I realized I accidentally sent you a command with `-a bar` in it. You'll want to replace that with your own app name.

You're right, I totally missed it. It worked just fine with `-a {app_name}`.

Anyway, I wrote to help@gigalixir.com to continue debugging the issue. I'm closing this one as it appears it's not an issue in `gigalixir-run` itself.

Thanks.
